name: Docker
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .dockerignore
jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Get Caddy version from Dockerfile
        id: version
        run:  echo "version=$(grep -Eo 'caddy:[0-9]+\.[0-9]+\.[0-9]+$' Dockerfile | cut -d ':' -f2)" | tee -a $GITHUB_OUTPUT
      - name: Generate Docker metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: |
            ghcr.io/Renaud11232/caddy
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ steps.version.outputs.version }}
            type=semver,pattern={{major}},value=v${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.title=caddy
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and upload Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
      - name: Push version tags
        env:
          CADDY_VERSION: ${{ steps.version.outputs.version }}
        run: |
          MAJOR=$(echo $CADDY_VERSION | cut -d . -f 1)
          MINOR=$(echo $CADDY_VERSION | cut -d . -f 2)
          git tag -f "v$MAJOR"
          git tag -f "v$MAJOR.$MINOR"
          git tag -f "v$CADDY_VERSION"
          git push -f -u origin "v$MAJOR"
          git push -f -u origin "v$MAJOR.$MINOR"
          git push -f -u origin "v$CADDY_VERSION"
